### PR TITLE
merge aliases and module dirs

### PR DESCRIPTION
**Pull request by tjdavenport**
Aliases from craco config or any craco plugins aren't being merged

### CODE REVIEW

**Comment by arodik** [comment]
@danielknell can we merge this fix? I've tested it, it works. This plugin is very helpful, but I can't use it without this fix :(

**Comment by tjdavenport** [comment]
> @danielknell can we merge this fix? I've tested it, it works. This plugin is very helpful, but I can't use it without this fix :(

Could use my fork until author can respond to this

**Comment by danielknell** [comment]
I will have a look tomorrow morning in sobriety and hopefully merge. Feel free to harass me if I forget.

**Review by danielknell — APPROVED** [review]

**Comment by danielknell** [comment]
merged and published.

**Pull request merged**
